name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - template: templates/install-jdk.yml

      - bash: |
          make sandbox &
          echo "Waiting for sandbox to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:9000/health 2>/dev/null || curl -f http://localhost:9000 2>/dev/null; then
              echo "Sandbox is ready after $i attempts"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Sandbox failed to start within 30 seconds"
              exit 1
            fi
            sleep 1
          done
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"

      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"