name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - template: templates/install-jdk.yml
      - bash: |
          set -eux
          ls -la bin || true
          make install-fhir-validator
          ls -lh bin || true
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"