name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - task: JavaToolInstaller@0
        displayName: Install JRE & JDK v17 x64
        inputs:
          versionSpec: "17"
          jdkArchitectureOption: "x64"
          jdkSourceOption: "LocalDirectory"
          jdkFile: "/tmp/openjdk/JAVA_HOME_17_X64_openjdk_tar.gz"
          jdkDestinationDirectory: "/tmp/openjdk"
      - bash: "make sandbox &"
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"
      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"
