name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Personal-Demographics-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      REQUIRE_ASID: false
      PDS_TARGET_SERVER: spine-demographics
      RATE_LIMIT_POST: true
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: templates/pds-tests.yml
      - environment: internal-qa-sandbox
        enable_status_monitoring: false
        proxy_path: sandbox
        post_deploy:
          - template: templates/sandbox-tests.yml
      - environment: int
        post_deploy:
           - template: templates/pds-tests-int.yml
        depends_on:
          - internal_dev
          - internal_qa_sandbox
      - environment: ref
        enable_status_monitoring: false # revert when /_status implemented or endpoint updated
        depends_on:
          - internal_dev
          - internal_qa_sandbox
        jinja_templates:
          REQUIRE_ASID: false
          PDS_TARGET_SERVER: spine-demographics
          RATE_LIMIT_POST: false
      - environment: sandbox
        proxy_path: sandbox
        enable_status_monitoring: false
        post_deploy:
          - template: templates/sandbox-tests.yml
        depends_on:
          - internal_dev
          - internal_qa_sandbox
      - environment: prod
        depends_on:
          - internal_dev
          - internal_qa_sandbox
        jinja_templates:
          REQUIRE_ASID: true
          PDS_TARGET_SERVER: spine-demographics
          RATE_LIMIT_POST: true
