name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - template: templates/install-jdk.yml

      - bash: |
          echo "=== Debugging make sandbox failure ==="
          echo "Checking npm and poetry installations..."
          npm --version || echo "npm not found"
          poetry --version || echo "poetry not found"
          
          echo "=== Trying npm run publish directly ==="
          npm run publish || echo "npm run publish failed with exit code: $?"
          
          echo "=== Checking build directory ==="
          ls -la build/ 2>/dev/null || echo "build directory does not exist"
          
          echo "=== Running make sandbox with verbose output ==="
          make sandbox 2>&1 || echo "make sandbox failed with exit code: $?"
        displayName: Debug Sandbox Startup Issues
        workingDirectory: "${{ variables.service_name }}"

      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"