name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Personal-Demographics-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    deploy_review_sandbox: true
    jinja_templates:
      PDS_TARGET_SERVER: spine-demographics
      REQUIRE_ASID: false
    secret_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_API_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_API_KEY
    secret_file_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_PRIVATE_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
      - ptl/app-credentials/jwt_testing/non-prod/ID_TOKEN_NHS_LOGIN_PRIVATE_KEY
    config_ids:
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_ID
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_SECRET
      - /ptl/azure-devops/personal-demographics/TEST_PATIENT_ID
    apigee_deployments:
        - environment: internal-dev
          make_spec_visible: true
          post_deploy:
            - template: templates/pds-tests.yml
        - environment: internal-dev
          service_name: ${{ variables.service_name }}-asid-required
          short_service_name: ${{ variables.short_service_name }}-asid
          product_display_name: ${{ variables.product_display_name }} (ASID Required)
          service_base_path: ${{ variables.service_base_path }}-asid-required
          stage_name: internal_dev_asid_required
          jinja_templates:
            PDS_TARGET_SERVER: spine-demographics
            REQUIRE_ASID: true
          post_deploy:
            - template: templates/pds-tests.yml
          depends_on:
            - internal_dev
        - environment: internal-dev-sandbox
          proxy_path: sandbox
          post_deploy:
            - template: templates/sandbox-tests.yml
        - environment: internal-dev
          service_name: ${{ variables.service_name }}-int
          short_service_name: ${{ variables.short_service_name }}-int
          product_display_name: ${{ variables.product_display_name }} (INT Testing)
          service_base_path: ${{ variables.service_base_path }}-int
          stage_name: internal_dev_int
          jinja_templates:
            PDS_TARGET_SERVER: spine-demographics-int
            REQUIRE_ASID: false
