name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - template: templates/install-jdk.yml

      - bash: |
          echo "=== Checking environment ==="
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Poetry version: $(poetry --version)"
          echo "Python version: $(python --version)"
          echo "Working directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          echo "=== Checking Makefile targets ==="
          make --version
          echo "Available make targets:"
          make -n sandbox || echo "Make sandbox failed in dry run"
          
          echo "=== Starting sandbox server ==="
          make sandbox &
          SANDBOX_PID=$!
          echo "Sandbox server started in background"
          sleep 5
          echo "Checking if sandbox process is still running..."
          if ps -p $SANDBOX_PID > /dev/null 2>&1; then
            echo "Sandbox process is running successfully"
          else
            echo "Sandbox process has terminated unexpectedly"
          fi
        displayName: Debug and start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"

      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"