name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    pre_steps:
      - bash: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.13 python3.13-venv python3.13-dev
          python3.13 --version
          echo "Configuring Poetry to use 3.13"
          poetry config keyring.enabled false
          poetry env use python3.13
        displayName: Install Python 3.13 (pre-setup)
    test_steps:
      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"