name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - bash: |
          echo "Setting JAVA_HOME to Java 17..."
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
        displayName: 'Manually set Java 17'
      - bash: "make sandbox &"
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make validate"
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"
