name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true # Run even if no recent changes

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'AzureStorage'
          jdkSourceUrl: 'https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz'
        displayName: 'Set up Java 17'
      - bash: "make sandbox &"
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"
      - bash: |
          java -version
          make validate
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"
