name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['master']
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - bash: "make sandbox &"
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make validate"
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"
