name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

schedules:
  - cron: "0 2 * * *"
    displayName: Daily Overnight Build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - template: templates/install-jdk.yml

      # Force clean npm install to avoid cache issues
      - bash: |
          echo "=== Cleaning any existing node_modules ==="
          rm -rf node_modules package-lock.json
          echo ""
          echo "=== Installing npm dependencies (fresh) ==="
          echo "Current directory: $(pwd)"
          npm install --no-optional --loglevel verbose
          echo ""
          echo "=== Verifying critical dependencies ==="
          ls -la node_modules/.bin/redocly || { echo "ERROR: redocly not installed"; exit 1; }
          node_modules/.bin/redocly --version || { echo "ERROR: redocly not executable"; exit 1; }
          echo ""
          echo "=== npm install completed successfully ==="
        displayName: Install npm dependencies (clean)
        workingDirectory: "${{ variables.service_name }}"
        # Always run, even if previous steps failed
        condition: succeededOrFailed()

      # Add explicit wait to ensure sandbox is ready
      - bash: |
          make sandbox &
          SANDBOX_PID=$!
          echo "Sandbox started with PID: $SANDBOX_PID"
          sleep 5
          echo "Sandbox should be ready"
        displayName: Start Sandbox Server
        workingDirectory: "${{ variables.service_name }}"

      # Add retry logic for the validation step
      - bash: |
          echo "=== Pre-validation checks ==="
          echo "Current directory: $(pwd)"
          ls -la node_modules/.bin/redocly || { echo "ERROR: redocly not found"; exit 1; }
          echo ""
          java -version
          echo ""
          echo "=== Running make validate (with retry) ==="
          
          # Retry logic for intermittent failures
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          until make validate || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
            RETRY_COUNT=$((RETRY_COUNT+1))
            echo "Validation failed. Retry $RETRY_COUNT of $MAX_RETRIES..."
            sleep 5
          done
          
          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
            echo "ERROR: Validation failed after $MAX_RETRIES attempts"
            exit 1
          fi
          
          echo "Validation successful!"
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"