name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    variables:
      PIP_CACHE_DIR: ".poetry"
    test_steps:
      - bash: "make sandbox &"
        displayName: Start Node JS Sandbox
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make validate"
        displayName: Validate FHIR
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make karate-sandbox &"
        displayName: Build and start Karate Sandbox container
        workingDirectory: "${{ variables.service_name }}"
        timeoutInMinutes: 5
        continueOnError: false
