name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

steps:
  - bash: poetry install
    workingDirectory: $(Pipeline.Workspace)/s
    displayName: Setup tests

  - template: templates/pds-tests-karate-overnight.yml
    parameters:
      environment: 'internal-dev'