name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Personal-Demographics-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    python_version: ${{ variables.python_version }}
    deploy_review_sandbox: true
    jinja_templates:
      PDS_TARGET_SERVER: spine-demographics
      REQUIRE_ASID: false
      RATE_LIMIT_POST: true
    apigee_deployments:
      - environment: internal-dev
        stage_name: karate_tests
        pre_deploy:
          - template: templates/install-jdk.yml
            parameters:
              service_name: ${{ variables.proxies_dir }}
        post_deploy:
          - template: templates/pds-tests-karate.yml

      - environment: internal-dev
        stage_name: pytest_bdd_tests
        post_deploy:
          - template: templates/pds-tests.yml
        depends_on:
          - karate_tests
      
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        stage_name: internal-dev-sandbox
        post_deploy:
          - template: templates/sandbox-tests.yml
          
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-int
        short_service_name: ${{ variables.short_service_name }}-int
        service_base_path: ${{ variables.service_base_path }}-int
        stage_name: internal_dev_int
        post_deploy:
           - template: templates/pds-tests-dev-int.yml  
        jinja_templates:
          PDS_TARGET_SERVER: spine-demographics-int
          REQUIRE_ASID: false
          RATE_LIMIT_POST: true