name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['master']
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: environment
    value: internal-dev
  - name: SERVICE_ARTIFACT_NAME
    value: ''
  - name: FULLY_QUALIFIED_SERVICE_NAME
    value: personal-demographics-internal-dev   
    
steps:
  - bash: poetry install
    workingDirectory: $(Pipeline.Workspace)/s
    displayName: Setup tests
  
  - task: Npm@1
    displayName: Install node packages
    inputs:
      command: 'install'
      workingDir: '$(Pipeline.Workspace)/s'

  - template: azure/components/get-aws-secrets-and-ssm-params.yml@common

  - template: azure/components/get-access-token.yml@common    

  - template: templates/pds-tests-karate.yml

  - template: templates/pds-tests.yml