name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ["master"]
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml
  - name: environment
    value: internal-dev
  - name: SERVICE_ARTIFACT_NAME
    value: ""
  - name: FULLY_QUALIFIED_SERVICE_NAME
    value: personal-demographics-internal-dev

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9"
      addToPath: true
      architecture: "x64"

  - bash: poetry install
    workingDirectory: $(Pipeline.Workspace)/s
    displayName: Setup tests

  - task: Npm@1
    displayName: Install node packages
    inputs:
      command: "install"
      workingDir: "$(Pipeline.Workspace)/s"

  - template: "azure/components/aws-assume-role.yml@common"
    parameters:
      role: "auto-ops"
      profile: "apm_ptl"

  - template: azure/components/get-aws-secrets-and-ssm-params.yml@common
    parameters:
      secret_file_ids:
        - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
        - ptl/app-credentials/jwt_testing/non-prod/PRIVILEGED_ACCESS_TESTING_SIGNING_KEY
      config_ids:
        - /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
      secret_ids:
        - ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
        - ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD

  - template: azure/components/get-mfa-code.yml@common
    parameters:
      apigee_otp_key: $(APIGEE_OTP_KEY)

  - template: azure/components/get-access-token.yml@common
    parameters:
      apigee_username: $(APIGEE_USERNAME)
      apigee_password: $(APIGEE_PASSWORD)

  - template: templates/pds-tests-karate.yml

  - template: templates/pds-tests.yml
