name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['master']
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: environment
    value: internal-dev
  - name: SERVICE_ARTIFACT_NAME
    value: ''
  - name: FULLY_QUALIFIED_SERVICE_NAME
    value: personal-demographics-internal-dev
    
steps:
  - bash: poetry install
    workingDirectory: $(Pipeline.Workspace)/s
    displayName: Setup tests
  
  - task: Npm@1
    displayName: Install node packages
    inputs:
      command: 'install'
      workingDir: '$(Pipeline.Workspace)/s'

  - template: "azure/components/aws-assume-role.yml@common"
    parameters:
     role: "auto-ops"
     profile: "apm_ptl"    

  - template: azure/components/get-aws-secrets-and-ssm-params.yml@common
    parameters:
     secret_file_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_PRIVATE_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
      - ptl/app-credentials/jwt_testing/non-prod/ID_TOKEN_NHS_LOGIN_PRIVATE_KEY
     config_ids:
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_ID
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_SECRET
      - /ptl/azure-devops/personal-demographics/TEST_PATIENT_ID
      - /ptl/azure-devops/personal-demographics/INTERNAL_SERVER_BASE_URI
      - /ptl/azure-devops/personal-demographics/AUTH_TOKEN_EXPIRY_MS
      - /ptl/azure-devops/personal-demographics/AUTH_TOKEN_EXPIRY_MS_INT
     secret_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_API_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_API_KEY
      - ptl/backends/ig3/INTERNAL_DEV_ASID

  - bash: |
      echo '##vso[task.setvariable variable=APIGEE_ENVIRONMENT]$(ENVIRONMENT)'
      echo '##vso[task.setvariable variable=PDS_BASE_PATH]$(SERVICE_BASE_PATH)'
      echo '##vso[task.setvariable variable=CLIENT_ID]$(CLIENT_ID)'
      echo '##vso[task.setvariable variable=CLIENT_SECRET]$(CLIENT_SECRET)'
      echo '##vso[task.setvariable variable=KEY_ID]test-1'
      echo '##vso[task.setvariable variable=TEST_PATIENT_ID]$(TEST_PATIENT_ID)'
      echo '##vso[task.setvariable variable=APPLICATION_RESTRICTED_SIGNING_KEY_PATH]$(Pipeline.Workspace)/secrets/$(JWT_TESTING_PRIVATE_KEY)'
      echo '##vso[task.setvariable variable=APPLICATION_RESTRICTED_WITH_ASID_SIGNING_KEY_PATH]$(Pipeline.Workspace)/secrets/$(JWT_TESTING_WITH_ASID_PRIVATE_KEY)'
      echo '##vso[task.setvariable variable=APPLICATION_RESTRICTED_API_KEY]$(JWT_TESTING_API_KEY)'
      echo '##vso[task.setvariable variable=APPLICATION_RESTRICTED_WITH_ASID_API_KEY]$(JWT_TESTING_WITH_ASID_API_KEY)'
      echo '##vso[task.setvariable variable=JWT_PRIVATE_KEY_ABSOLUTE_PATH]$(Pipeline.Workspace)/secrets/$(JWT_TESTING_PRIVATE_KEY)'
      echo '##vso[task.setvariable variable=ID_TOKEN_NHS_LOGIN_PRIVATE_KEY_ABSOLUTE_PATH]$(Pipeline.Workspace)/secrets/$(ID_TOKEN_NHS_LOGIN_PRIVATE_KEY)'
      echo '##vso[task.setvariable variable=AUTH_TOKEN_EXPIRY_MS]$(AUTH_TOKEN_EXPIRY_MS)'
      echo '##vso[task.setvariable variable=AUTH_TOKEN_EXPIRY_MS_INT]$(AUTH_TOKEN_EXPIRY_MS_INT)'
      echo '##vso[task.setvariable variable=REDIRECT_URI]https://example.org/callback'
      echo '##vso[task.setvariable variable=APIGEE_API_TOKEN]$(secret.AccessToken)'
      if [ -z "$(SERVICE_ARTIFACT_NAME)" ]; then
        echo '##vso[task.setvariable variable=ARTIFACT_PATH]$(Pipeline.Workspace)/s/'
      else
        echo '##vso[task.setvariable variable=ARTIFACT_PATH]$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/'
      fi
    displayName: Expose common variables
    
  - template: azure/components/get-mfa-code.yml  
    parameters:
     apigee_otp_key: "ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY"
    
  - template: azure/components/get-access-token.yml@common 
    parameters:
     apigee_username: "ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME"
     apigee_password: "ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD"

  - template: templates/pds-tests-karate.yml

  - template: templates/pds-tests.yml