variables:
  service_name: personal-demographics
  short_service_name: pds
  service_base_path: personal-demographics/FHIR/R4-pr-697
  product_display_name: Personal Demographics Service
  product_description: " "
  spec_file: personal-demographics.json
