type: object
description: Metadata about this resource.
properties:
  versionId:
    type: string
    description: The NHS Digital assigned version of the patient resource.
    example: "2"
  security:
    type: array
    description: |
      The level of security on the patients record, which affects which fields are populated on retrieval. The possible responses are:
      * U - unrestricted. All available data is returned.
      * R - restricted. Any sensitive data around the patient's location, so `address`, `generalPractitioner` and `telecom`, are removed from the response.
      * REDACTED - redacted. The patient record has been marked as invalid, so the data should not be used. This code is never returned; you receive a 404, and appropriate error response, if an invalidated patient retrieval is attempted.
    maxItems: 1
    items:
      type: object
      properties:
        system:
          type: string
          description: URI of the value set specification.
          example: http://terminology.hl7.org/CodeSystem/v3-Confidentiality
        code:
          type: string
          description: Code defined by the system value set.
          enum: [U, R, V, REDACTED]
          example: U
        display:
          type: string
          description: Representation defined by the system.
          enum: ["unrestricted", "restricted", "redacted"]
          example: unrestricted
